- name: create multiple users
  hosts: node2.example.com
  vars_files:
    - 17userlist


  tasks:
    - name: create users
      user:
        name: "{{ item.username }}"
        comment: "{{ item.comment }}"
        shell: "{{ item.shell }}"
        state: present
      loop: "{{ users }}"