- name: create multiple users
  hosts: node2.example.com
  vars_files:
    - 17userlistencrypted
    
  tasks:
    - name: create users
      user:
        name: "{{ item.username }}"
        comment: "{{ item.comment }}"
        shell: "{{ item.shell }}"
        state: present
        password: "{{ item.password | password_hash('sha512')}}"
      loop: "{{ users }}"