- name: create multiple users
  hosts: node2.example.com
  vars_files:
    - 17userlist
  vars_prompt:
    - name: my_password2
      prompt: Enter password2
      private: true
      #encrypt: sha512_crypt
      #confirm: true
      #salt_size: 7
    
  tasks:
    - name: create users
      user:
        name: "{{ item.username }}"
        comment: "{{ item.comment }}"
        shell: "{{ item.shell }}"
        state: present
        password: "{{ my_password2 | password_hash('sha512') }}"
      loop: "{{ users }}"