- name: install web server based on OS_family
  hosts: servers
  tasks: 
    - name: install httpd if RedHat family OS
      yum:
        name: httpd
        state: absent
      loop: "{{ ansible_mounts }}"
      when: item.mount == "/" and item.size_available > 5000000
      

    - name: install httpd if Debian family OS
      yum:
        name: httpd
        state: latest
      when: ansible_os_family == "Debian"