- name: Install and set home page on servers
  hosts: servers
  tasks:
    - name: "T1 - install web server {{ pkg1 }} package"
      package: 
        name: "{{ pkg1 }}"
        state: present
    # - name: "T2 start {{ pkg1 }} service"
    #   service:
    #     name: "{{ pkg1 }}"
    #     state: started
    #     enabled: true